######################## default configuration ####################
baseURL = "/"
languageCode = "en-us"
title = "DoctoraPeke Blog"
theme = "liva-hugo"
summaryLength = "10"
paginate = 6
disqusShortname = ""

[outputs]
  home = ["HTML", "RSS", "JSON"]

############################# Plugins ##############################
[params.plugins]

  # CSS Plugins
  [[params.plugins.css]]
  URL = "plugins/bootstrap/bootstrap.min.css"
  [[params.plugins.css]]
  URL = "plugins/slick/slick.css"
  [[params.plugins.css]]
  URL = "plugins/themify-icons/themify-icons.css"
  [[params.plugins.css]]
  URL = "plugins/venobox/venobox.css"

  # JS Plugins
  [[params.plugins.js]]
  URL = "plugins/jQuery/jquery.min.js"
  [[params.plugins.js]]
  URL = "plugins/bootstrap/bootstrap.min.js"
  [[params.plugins.js]]
  URL = "plugins/slick/slick.min.js"
  [[params.plugins.js]]
  URL = "plugins/venobox/venobox.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/fuse.min.js"
  [[params.plugins.js]]
  URL = "plugins/search/mark.js"
  [[params.plugins.js]]
  URL = "plugins/search/search.js"

  
############################## navigation ###############################
[menu]
  
  # main menu
  [[menu.main]]
  name = "Acerca de mi"
  URL = "about"
  weight = 1
  
  [[menu.main]]
  name = "Post"
  URL = "blog"
  weight = 2
  
  [[menu.main]]
  name = "Contacto"
  URL = "contact"
  weight = 3

  # footer menu
  [[menu.footer]]
  name = "Acerca de mi"
  URL = "about"
  weight = 1
  
  [[menu.footer]]
  name = "Post"
  URL = "blog"
  weight = 2
  
  [[menu.footer]]
  name = "Contacto"
  URL = "contact"
  weight = 3


#################### default parameters ################################
[params]
logo = "images/logo.png"
home = "Inicio"
# Meta data
description = "blog de cuidado infantil"
author = "DoctoraPeke"
# Google Analitycs
googleAnalitycsID = "Your ID"
# Contact Information
mobile = "0124857985320"
email = "doctorapeke@email.com"
location = "Rancagua, Chile"
# copyright
copyright = "| copyright &copy; 2020 [Piztek](https://piztek.com) All Rights Reserved |"

############################# categorias ########################
categories = ["Alimentos", "Emergencias", "Dia a dia"]


  # Preloader
  [params.preloader]
  enable = true
  preloader = "" # use .png , .svg or .gif format

  # search
  [params.search]
  enable = true

############################ news letter ########################
[params.newsletter]
enable = true
title = "Unete a nuestro Boletin"
content = "Lorem ipsum dolor sit amet, consetetur sadipscing elitr, sed diam nonumy eirmod tempor invidunt ut labore et dolore magna aliquyam erat, sed diam voluptua. At vero"

############################# social site ########################
[[params.social]]
title = "facebook"
icon = "ti-facebook" # themify icon : https://themify.me/themify-icons
link = "https://www.facebook.com/DoctoraPeke"

[[params.social]]
title = "twitter"
icon = "ti-twitter-alt" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/doctorapeke"

[[params.social]]
title = "instagram"
icon = "ti-instagram" # themify icon : https://themify.me/themify-icons
link = "https://www.instagram.com/doctorapeke/"

